vulnerabilities:
- id: CVE-2023-2650
  statement: justification why this exception is needed
  expired_at: 2024-09-01

misconfigurations:
- id: AVD-DS-0002
  statement: justification why this exception is needed
  paths:
    - "docs/Dockerfile"
  expired_at: 2024-09-01